### ISSUE TITLE
Tracking: Static Site generation support in wp-now

### ISSUE THREAD

**Issue by adamziel** [WordPress/playground-tools#238]
This is a single issue to keep track of all the wp-now limitations listed in https://github.com/adamziel/playground-docs-workflow/pull/48. Let's turn those into separate issues.

- [ ] #239
- [ ] https://github.com/WordPress/playground-tools/issues/26
- [ ] https://github.com/WordPress/playground-tools/issues/245
- [ ] https://github.com/WordPress/playground-tools/issues/73
- [ ] #244
- [ ] https://github.com/WordPress/playground-tools/issues/240
- [ ] https://github.com/WordPress/playground-tools/issues/220
- [ ] #243
- [ ] #241
- [ ] #242
